[package]
name = "bliss-html"
version.workspace = true
description = "Bliss HTML parser"
documentation = "https://docs.rs/bliss-html"
license.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true

[dependencies]
bliss-dom = { path = "../bliss-dom" }
bliss-traits = { path = "../bliss-traits" }

# Servo dependencies
html5ever = "0.37.0"
xml5ever = "0.37.0"
